Реализация профиля и логаута
maximumtest/360 pull request #84
Opened 2019-06-05 14:52 UTC by lo2s

closes #82 
closes #83

2019-06-05 15:18 UTC, mgs640 commented on app/Http/Controllers/V1/UserController.php
> +                $user->dropAvatar();
@lo2s может быть очищение параметра avatar перенести сразу в этот метод?

2019-06-05 15:18 UTC, mgs640 commented on app/Http/Controllers/V1/UserController.php
> +                $avatar = Storage::cloud()->putFile('users/avatars', $request->file('avatar'));
@lo2s и может быть загрузку аватарки вынести до ее удаления? чтоб если что не так пойдет, юзер не лишился своей прошлось аватарки.

2019-06-05 15:18 UTC, mgs640 commented on app/User.php
> +    public function getAvatarAttribute($value)
@lo2s а зачем тут параметр `$value` ?

2019-06-05 15:29 UTC, lo2s commented on app/User.php
> +    public function getAvatarAttribute($value)
@mgs640 т.к. поле "avatar" действительно существует, его значение можно получить через $value)

2019-06-05 15:35 UTC, lo2s commented on app/Http/Controllers/V1/UserController.php
> +                $avatar = Storage::cloud()->putFile('users/avatars', $request->file('avatar'));
@mgs640 отличная идея) спасибо, исправил)

2019-06-05 15:36 UTC, lo2s commented on app/Http/Controllers/V1/UserController.php
> +                $user->dropAvatar();
@mgs640 добавил `$this->avatar = ''` внутрь метода... или ты что-то другое имел ввиду?)

2019-06-05 15:42 UTC, valsaven requested changes
В остальном LGTM

2019-06-05 15:42 UTC, valsaven commented on resources/assets/js/layouts/Default.vue
> +    const response = await this.logout();
@lo2s Может логичнее всё в едином ключе назвать? Или logout или signout?

2019-06-05 15:45 UTC, mgs640 approved these changes

2019-06-06 07:17 UTC, lo2s commented on resources/assets/js/layouts/Default.vue
> +    const response = await this.logout();
@valsaven если их назвать одинаково, то как из 1 будешь ссылаться на другой?) это же вроде конфликт имен будет, разве нет?)

2019-06-06 07:38 UTC, evgeniakuzina commented on app/Http/Controllers/V1/UserController.php
> +        $user->save();
@lo2s а почему сохранение модели в блок try не вынести? Если вдруг не сохранится)

2019-06-06 07:40 UTC, evgeniakuzina commented on app/Http/Requests/V1/User/UpdateProfileRequest.php
> +            'avatar' => 'image|nullable|sometimes',
@lo2s если не ошибаюсь, sometimes используется только вместе с [required](https://laravel.com/docs/5.7/validation#conditionally-adding-rules)

2019-06-06 07:42 UTC, evgeniakuzina commented on app/User.php
> +            return Storage::cloud()->delete($this->avatarSrc);
@lo2s не хватает пустой строки перед return

2019-06-06 07:45 UTC, evgeniakuzina commented on routes/api.php
> +        Route::post('users/drop-avatar', 'UserController@dropAvatar');
@lo2s а экшена dropAvatar вроде бы нет в UserController?

2019-06-06 07:47 UTC, lo2s commented on app/Http/Controllers/V1/UserController.php
> +        $user->save();
@evgeniakuzina спасибо, исправил, и правда лишним не будет)

2019-06-06 07:49 UTC, lo2s commented on app/Http/Requests/V1/User/UpdateProfileRequest.php
> +            'avatar' => 'image|nullable|sometimes',
@evgeniakuzina спасибо, исправил) без required оно и правда лишено смысла, т.к. поля в запросе не являются обязательными по умолчанию)

2019-06-06 07:49 UTC, lo2s commented on app/User.php
> +            return Storage::cloud()->delete($this->avatarSrc);
@evgeniakuzina спасибо, добавил отступ)

2019-06-06 07:50 UTC, lo2s commented on routes/api.php
> +        Route::post('users/drop-avatar', 'UserController@dropAvatar');
@evgeniakuzina и снова спасибо) забыл удалить)

2019-06-06 07:55 UTC, evgeniakuzina approved these changes

2019-06-06 08:49 UTC, valsaven commented on resources/assets/js/layouts/Default.vue
> +    const response = await this.logout();
@lo2s Да, логично.

2019-06-06 08:49 UTC, valsaven approved these changes

2019-06-06 08:50 UTC, merged