Добавление грида для пользователей
maximumtest/360 pull request #88
Opened 2019-06-25 15:43 UTC by lo2s

2019-06-25 21:28 UTC, valsaven requested changes

2019-06-25 21:28 UTC, valsaven commented on package.json
> +    "jsgrid": "^1.5.3",
@lo2s А без него не обойтись? Нам точно стоит jQuery тащить?

2019-06-25 21:28 UTC, valsaven commented on resources/assets/js/views/Admin.vue
> +import 'jsgrid/external/jquery/jquery-1.8.3';
@lo2s Ну... такое. Может лучше отсюда утащить компонент и переделать под наши нужды? https://vuetifyjs.com/en/components/data-tables

2019-06-26 16:49 UTC, lo2s commented on resources/assets/js/views/Admin.vue
> +import 'jsgrid/external/jquery/jquery-1.8.3';
@valsaven я сам не в восторге от jsgrid, но внутри vue-material нет ничего схожего по функционалу, это было самое простое и функциональное решение, которое нашел) как по мне, пока не совсем поздно, лучше перейти на vuetify, vue-bootstrap или писать свои компоненты, потому что vue-material ужасен)

2019-06-27 13:45 UTC, merged

2019-06-27 13:46 UTC, MooGeek commented
Влил для теста функционала. Видимо, будем менять библиотеку компонент - там и порефакторим